### ISSUE TITLE
TypeError: Da is undefined

### ISSUE THREAD

**Issue by joho1968** [makryl/ABigImage#2]
Using the latest jQuery 3 and BootStrap 3, both loaded before ABI, I get a "TypeError: Da is undefined" in the WebConsole of Firefox (Linux). This is using the .min.js version. Using the plain .js version, I get another error, "boxe" is undefined on line 91.

**Comment by makryl** [comment]
I will check it soon. Would be great if you can provide link to test page with non-minified version.

**Comment by joho1968** [comment]
Hello, I don't have a public test page available yet for this. Are you saying that you cannot duplicate this? Because I did very little except include latest jQuery 3.x and then your abigimage.jquery.js, and got these warnings/errors.

**Comment by makryl** [comment]
I found that this error is not related to jQuery v3.
I will make fix for this soon.
As workaround for now, you should place script
```<script src="abigimage.jquery.js"></script>```
in `body`, not in `head`

**Comment by makryl** [comment]
if you place script in `head` you also can use `defer` attribute
```<script defer src="abigimage.jquery.js"></script>```

**Comment by makryl** [comment]
you can forget about workarounds, fixed in new version 2.1.1
